apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: web-app-pipeline
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: run-npm-install
      taskRef:
        name: npm-install
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: run-jasmine-test
      taskRef:
        name: jasmine-test
      runAfter:
        - run-npm-install
      workspaces:
        - name: source
          workspace: shared-workspace
---